src/src/Models/DeletedDatas.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace src.Models
{
    public class DeletedDatas
    {

        public int Id { get; set; }

        public DateTime DateDeleted { get; set; }

        public int ControlNumber { get; set; }

        public string Origin { get; set; }

        public string FullName { get; set; }

        public string DeletedBy { get; set; }

        public string Remarks { get; set; }

        public int? Amount { get; set; }
    }
}

src/src/Controllers/Api/AuditTrailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json.Linq;
using src.Data;
using src.Models;
using src.Services;

namespace src.Controllers.Api
{
    [Produces("application/json")]
    [Route("api/AuditTrail")]
    //[Authorize]
    public class AuditTrailController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IDotnetdesk _dotnetdesk;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IEmailSender _emailSender;
        private readonly SignInManager<ApplicationUser> _signInManager;



        public AuditTrailController(ApplicationDbContext context,
            IDotnetdesk dotnetdesk,
            UserManager<ApplicationUser> userManager,
            IEmailSender emailSender,
            SignInManager<ApplicationUser> signInManager)
        {
            _context = context;
            _dotnetdesk = dotnetdesk;
            _userManager = userManager;
            _emailSender = emailSender;
            _signInManager = signInManager;
        }

        // GET: api/AuditTrail
        [HttpGet("GetDeletedDatas")]
        public IActionResult GetDeletedDatas([FromRoute]Guid organizationId)
        {
            var deleted = _context.DeletedDatas.OrderByDescending(x => x.Id).ToList();
            return Json(new { data = deleted });
        }

        // GET: api/AuditTrail
        [HttpGet("GetEditedDatas")]
        public IActionResult GetEditedDatas([FromRoute]Guid organizationId)
        {
            var edited = _context.EditedDatas.OrderByDescending(x => x.Id).ToList();
            return Json(new { data = edited });
        }

    }
}

src/src/Controllers/AuditTrailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using src.Data;
using src.Models;

namespace src.Controllers
{
    [Authorize]
    public class AuditTrailController : BaseDotnetDeskController
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public AuditTrailController(ApplicationDbContext context,
            UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }


        public async Task<IActionResult> Index(Guid org)
        {
            if (org == Guid.Empty)
            {
                org = Guid.NewGuid();
                //return NotFound();
            }
            ApplicationUser appUser = await _userManager.GetUserAsync(User);

            Organization organization = _context.Organization.Where(x => x.organizationId.Equals(org)).FirstOrDefault();
            ViewData["org"] = org;
            return View(organization);
        }

        public async Task<IActionResult> DeletedDatas(Guid org)
        {
            if (org == Guid.Empty)
            {
                org = Guid.NewGuid();
                //return NotFound();
            }
            ApplicationUser appUser = await _userManager.GetUserAsync(User);

            Organization organization = _context.Organization.Where(x => x.organizationId.Equals(org)).FirstOrDefault();
            ViewData["org"] = org;
            return View(organization);
        }

        //public IActionResult AddEditIndex(Guid org, Guid id)
        //{
        //    if (id == Guid.Empty)
        //    {
        //        Subject subject = new Subject();
        //        //ticketing.ticketingId = org;
        //        return View(subject);
        //    }
        //    else
        //    {
        //        return View(_context.Subject.Where(x => x.Id.Equals(id)).FirstOrDefault());
        //    }

        //}



    }
}

src/src/Views/AuditTrail/DeletedDatas.cshtml
@model src.Models.Organization
@inject UserManager<ApplicationUser> UserManager
@{
    ViewData["Title"] = "Audit Trail";
    ApplicationUser appUser = await UserManager.GetUserAsync(User);
    Layout = "_LayoutAdminlteAdmin";
}
    <style>
        .btn-primary {
            background-color: #3c8dbc;
            border-color: #367fa9;
        }

        .btn-default:active, .btn-default.active, .open > .dropdown-toggle.btn-default {
    color: #333;
    background-color: #3c8dbc;
    border-color: #adadad;
}

        .btn-lg, .btn-group-lg > .btn {
            padding: 10px 16px;
            font-size: 14px;
            line-height: 1.8;
            border-radius: 6px;
        }

        .audit {
    border-left: 3px solid #3c8dbc;
    color: #ccc !important;
    background: #1e282c;
}
    </style>
<!-- Content Header (Page header) -->
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-lg-12">
            <div class="box box-primary">
                <div class="box-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <a class="header btn-default btn-lg" href="@Url.Action("Index","AuditTrail")">Edited data</a> &nbsp;
                            <a class="header btn-default btn-lg active" href="@Url.Action("DeletedDatas","AuditTrail")">Deleted data</a>
                            <input type="hidden" asp-for="@Model.organizationId" />
                            <table id="grid" name="grid" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th class="col-md-1">Datetime deleted</th>
                                        @*<th class="col-md-1">Plate number</th>*@
                                        <th class="col-md-1">From</th>
                                        <th class="col-md-1">Name</th>
                                        <th class="col-md-1">Deleted by</th>
                                        <th class="col-md-1">Amount</th>
                                        <th class="col-md-1">Remarks</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>

</section>

<!-- /.content -->
<!--modal placeholder-->
@*<div class="modal modal-primary fade" id="modalDefault">
        <div class="modal-dialog">
            <div class="modal-content">

            </div>
        </div>
    </div>*@



@section Scripts{
    @await Html.PartialAsync("_ValidationScriptsPartial")

    <script src="~/js/views/auditTrail/deletedDatas.js"></script>
}

src/src/Views/AuditTrail/Index.cshtml
@model src.Models.Organization
@inject UserManager<ApplicationUser> UserManager
@{
    ViewData["Title"] = "Audit Trail";
    ApplicationUser appUser = await UserManager.GetUserAsync(User);
    Layout = "_LayoutAdminlteAdmin";
}
    <style>
        .btn-primary {
            background-color: #3c8dbc !important;
            border-color: #367fa9 !important;
        }

        .btn-default:active, .btn-default.active, .open > .dropdown-toggle.btn-default {
            color: #333 !important;
            background-color: #3c8dbc !important;
            border-color: #adadad !important;
        }

        .btn-lg, .btn-group-lg > .btn {
            padding: 10px 16px !important;
            font-size: 14px !important;
            line-height: 1.8 !important;
            border-radius: 6px !important;
        }

        .audit {
            border-left: 3px solid #3c8dbc !important;
            color: white !important;
            background: #1e282c !important;
        }

        .skin-blue .sidebar-menu>li.active>a {
    border-left-color: rgba(0,0,0,0.1) !important;
}
.skin-blue .sidebar-menu>li:hover>a, .skin-blue .sidebar-menu>li.active>a, .skin-blue .sidebar-menu>li.menu-open>a {
    color: #b8c7ce !important;
    background: #1e282c; 
}
    </style>
@*<style>
    .btn-primary {
    background-color: #3c8dbc;
    border-color: #367fa9;
}

.btn-default:active, .btn-default.active, .open > .dropdown-toggle.btn-default {
    color: #333;
    background-color: #3c8dbc;
    border-color: #adadad;
}

    .btn-lg, .btn-group-lg > .btn {
    padding: 10px 16px;
    font-size: 14px;
    line-height: 1.8;
    border-radius: 6px;
}
</style>*@
<!-- Content Header (Page header) -->
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-lg-12">
            <div class="box box-primary">
                <div class="box-body">
                    <div class="row">
                        <div class="col-lg-12">
                            @*<div class="col-md-6">
            <a class="btn btn-success" style="margin-bottom:10px" onclick="ShowPopup('@Url.Action("AddEditIndex","Members")')"><i class="fa fa-plus"></i> New Personnel</a>
        </div>*@
                            <a class="header btn-default btn-lg @Html.IsSelected(controller: "AuditTrail", action: "Index")" href="@Url.Action("Index","AuditTrail")">Edited data</a> &nbsp;
                            <a class="header btn-default btn-lg @Html.IsSelected(controller: "AuditTrail", action: "DeletedDatas")" href="@Url.Action("DeletedDatas","AuditTrail")">Deleted data</a>

                            <input type="hidden" asp-for="@Model.organizationId" />
                            <table id="grid" name="grid" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th class="col-md-1">Datetime edited</th>
                                        <th class="col-md-1">Control number</th>
                                        <th class="col-md-1">From</th>
                                        <th class="col-md-1">Original datas</th>
                                        <th class="col-md-1">Edited by</th>
                                        <th class="col-md-1">Remarks</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>

</section>

<!-- /.content -->
<!--modal placeholder-->
@*<div class="modal modal-primary fade" id="modalDefault">
        <div class="modal-dialog">
            <div class="modal-content">

            </div>
        </div>
    </div>*@



@section Scripts{
    @await Html.PartialAsync("_ValidationScriptsPartial")

    <script src="~/js/views/auditTrail/index.js"></script>
}